package at.uastw.resourcesgamehelper

object GameData {
    val items = listOf(
        GameItem(1, "credits", "https://api.resources-game.ch/resimg/res1.png"),
        GameItem(2, "Clay", "https://api.resources-game.ch/resimg/res2.png", 540090.0, 1530.0),
        GameItem(3, "Gravel", "https://api.resources-game.ch/resimg/res3.png", 256908.0, 542.0),
        GameItem(4, "Clay Pit", null),
        GameItem(5, "Gravel Pit", null),
        GameItem(6, "Concrete Factory", "https://api.resources-game.ch/resimg/res6.png"),
        GameItem(7, "Concrete", "https://api.resources-game.ch/resimg/res7.png"),
        GameItem(8, "Coal", "https://api.resources-game.ch/resimg/res8.png", 1250520.0, 510.0),
        GameItem(9, "Coal Mine", null),
        GameItem(10, "Crude Oil", "https://api.resources-game.ch/resimg/res10.png", 773874.0, 306.0),
        GameItem(11, "Oil Derrick", null),
        GameItem(12, "Bauxite", "https://api.resources-game.ch/resimg/res12.png", 673506.0, 306.0),
        GameItem(13, "Iron Ore", "https://api.resources-game.ch/resimg/res13.png", 556956.0, 382.5),
        GameItem(14, "Gold Ore", "https://api.resources-game.ch/resimg/res14.png", 1970640.0, 2040.0),
        GameItem(15, "Silver Ore", "https://api.resources-game.ch/resimg/res15.png", 914732.0, 637.5),
        GameItem(16, "Bauxite Mine", null),
        GameItem(17, "Iron Ore Mine", null),
        GameItem(18, "Gold Mine", null),
        GameItem(19, "Silver Mine", null),
        GameItem(20, "Limestone", "https://api.resources-game.ch/resimg/res20.png", 253470.0, 510.0),
        GameItem(21, "Limestone Quarry", null),
        GameItem(22, "Fertilizer", "https://api.resources-game.ch/resimg/res22.png"),
        GameItem(23, "Fertilizer Factory", "https://api.resources-game.ch/resimg/res23.png"),
        GameItem(24, "Bricks", "https://api.resources-game.ch/resimg/res24.png"),
        GameItem(25, "Brick Factory", "https://api.resources-game.ch/resimg/res25.png"),
        GameItem(26, "Chalcopyrite", "https://api.resources-game.ch/resimg/res26.png", 552432.0, 408.0),
        GameItem(27, "Copper Mine", null),
        GameItem(28, "Insecticides", "https://api.resources-game.ch/resimg/res28.png"),
        GameItem(29, "Insecticide Factory", "https://api.resources-game.ch/resimg/res29.png"),
        GameItem(30, "Steel", "https://api.resources-game.ch/resimg/res30.png"),
        GameItem(31, "Ironworks", "https://api.resources-game.ch/resimg/res31.png"),
        GameItem(32, "Aluminium", "https://api.resources-game.ch/resimg/res32.png"),
        GameItem(33, "Aluminium Factory", "https://api.resources-game.ch/resimg/res33.png"),
        GameItem(34, "Silver Refinery", "https://api.resources-game.ch/resimg/res34.png"),
        GameItem(35, "Silver", "https://api.resources-game.ch/resimg/res35.png"),
        GameItem(36, "Copper", "https://api.resources-game.ch/resimg/res36.png"),
        GameItem(37, "Copper Refinery", "https://api.resources-game.ch/resimg/res37.png"),
        GameItem(38, "Fossil Fuel", "https://api.resources-game.ch/resimg/res38.png"),
        GameItem(39, "Oil Refinery", "https://api.resources-game.ch/resimg/res39.png"),
        GameItem(40, "Roman Coins", "https://api.resources-game.ch/resimg/res40.png"),
        GameItem(41, "Fossils", "https://api.resources-game.ch/resimg/res41.png"),
        GameItem(42, "Giant Diamond", "https://api.resources-game.ch/resimg/res42.png"),
        GameItem(43, "Maintenance Kit", "https://api.resources-game.ch/resimg/res43.png"),
        GameItem(44, "Tech Upgrade 1", "https://api.resources-game.ch/resimg/res44.png"),
        GameItem(45, "Tech Upgrade 2", "https://api.resources-game.ch/resimg/res45.png"),
        GameItem(46, "Tech Upgrade 3", "https://api.resources-game.ch/resimg/res46.png"),
        GameItem(48, "Tech Upgrade 4", "https://api.resources-game.ch/resimg/res48.png"),
        GameItem(49, "Ilmenite", "https://api.resources-game.ch/resimg/res49.png", 86520.0, 280.5),
        GameItem(50, "Ilmenite Mine", null),
        GameItem(51, "Titanium", "https://api.resources-game.ch/resimg/res51.png"),
        GameItem(52, "Titanium Refinery", "https://api.resources-game.ch/resimg/res52.png"),
        GameItem(53, "Quartz Sand", "https://api.resources-game.ch/resimg/res53.png", 276165.0, 765.0),
        GameItem(54, "Sand Mine", null),
        GameItem(55, "Copper Coins", "https://api.resources-game.ch/resimg/res55.png"),
        GameItem(57, "Old Tires", "https://api.resources-game.ch/resimg/res57.png"),
        GameItem(58, "Plastics", "https://api.resources-game.ch/resimg/res58.png"),
        GameItem(59, "Recycling Plant", "https://api.resources-game.ch/resimg/res59.png"),
        GameItem(60, "Glass", "https://api.resources-game.ch/resimg/res60.png"),
        GameItem(61, "Glazier's Workshop", "https://api.resources-game.ch/resimg/res61.png"),
        GameItem(62, "Casino", "https://api.resources-game.ch/resimg/res62.png"),
        GameItem(63, "Plastic Factory", "https://api.resources-game.ch/resimg/res63.png"),
        GameItem(65, "Museum", "https://api.resources-game.ch/resimg/res65.png"),
        GameItem(66, "Electronics", "https://api.resources-game.ch/resimg/res66.png"),
        GameItem(67, "Silicon", "https://api.resources-game.ch/resimg/res67.png"),
        GameItem(68, "Silicon Refinery", "https://api.resources-game.ch/resimg/res68.png"),
        GameItem(69, "Electronics Factory", "https://api.resources-game.ch/resimg/res69.png"),
        GameItem(70, "Scrap Metal", "https://api.resources-game.ch/resimg/res70.png"),
        GameItem(71, "Hospital", "https://api.resources-game.ch/resimg/res71.png"),
        GameItem(72, "Law Firm", "https://api.resources-game.ch/resimg/res72.png"),
        GameItem(74, "Used Oil", "https://api.resources-game.ch/resimg/res74.png"),
        GameItem(75, "Medical Technology", "https://api.resources-game.ch/resimg/res75.png"),
        GameItem(76, "Medical Technology Inc.", "https://api.resources-game.ch/resimg/res76.png"),
        GameItem(77, "Plastic Scrap", "https://api.resources-game.ch/resimg/res77.png"),
        GameItem(78, "Electronic Scrap", "https://api.resources-game.ch/resimg/res78.png"),
        GameItem(79, "Gold", "https://api.resources-game.ch/resimg/res79.png"),
        GameItem(80, "Gold Refinery", "https://api.resources-game.ch/resimg/res80.png"),
        GameItem(81, "Rough Diamonds", "https://api.resources-game.ch/resimg/res81.png", 4300575.0, 1275.0),
        GameItem(82, "Diamond Mine", null),
        GameItem(84, "Jewellery", "https://api.resources-game.ch/resimg/res84.png"),
        GameItem(85, "Goldsmith", "https://api.resources-game.ch/resimg/res85.png"),
        GameItem(86, "Mafia HQ", "https://api.resources-game.ch/resimg/res86.png"),
        GameItem(87, "Weapons", "https://api.resources-game.ch/resimg/res87.png"),
        GameItem(89, "Lithium Ore Mine", null),
        GameItem(90, "Lithium Ore", "https://api.resources-game.ch/resimg/res90.png", 1026120.0, 2040.0),
        GameItem(91, "Lithium Refinery", "https://api.resources-game.ch/resimg/res91.png"),
        GameItem(92, "Lithium", "https://api.resources-game.ch/resimg/res92.png"),
        GameItem(93, "Batteries", "https://api.resources-game.ch/resimg/res93.png"),
        GameItem(95, "Battery Factory", "https://api.resources-game.ch/resimg/res95.png"),
        GameItem(96, "Watch Dogs", "https://api.resources-game.ch/resimg/res96.png"),
        GameItem(97, "Training Camp", "https://api.resources-game.ch/resimg/res97.png"),
        GameItem(98, "Security Staff", "https://api.resources-game.ch/resimg/res98.png"),
        GameItem(99, "Elite Force", "https://api.resources-game.ch/resimg/res99.png"),
        GameItem(101, "Arms Factory", "https://api.resources-game.ch/resimg/res101.png"),
        GameItem(102, "Attack Dogs", "https://api.resources-game.ch/resimg/res102.png"),
        GameItem(103, "Gangster", "https://api.resources-game.ch/resimg/res103.png"),
        GameItem(104, "Private Army", "https://api.resources-game.ch/resimg/res104.png"),
        GameItem(115, "Waste Glass", "https://api.resources-game.ch/resimg/res115.png"),
        GameItem(116, "Tech Center", "https://api.resources-game.ch/resimg/res116.png"),
        GameItem(117, "Scan Drones", "https://api.resources-game.ch/resimg/res117.png"),
        GameItem(118, "Drone Shipyard", "https://api.resources-game.ch/resimg/res118.png"),
        GameItem(119, "Drone Research", "https://api.resources-game.ch/resimg/res119.png"),
        GameItem(120, "Drone Wreckage", "https://api.resources-game.ch/resimg/res120.png"),
        GameItem(121, "Service Center", "https://api.resources-game.ch/resimg/res121.png"),
        GameItem(122, "HR Department", "https://api.resources-game.ch/resimg/res122.png"),
        GameItem(123, "Haulage firm", "https://api.resources-game.ch/resimg/res123.png"),
        GameItem(124, "Trucks", "https://api.resources-game.ch/resimg/res124.png"),
        GameItem(125, "Truck plant", "https://api.resources-game.ch/resimg/res125.png"),
        GameItem(126, "Fire Station", "https://api.resources-game.ch/resimg/res126.png"),
        GameItem(127, "Seismology Centre", "https://api.resources-game.ch/resimg/res127.png"),
        GameItem(158, "Night Shift", "https://api.resources-game.ch/resimg/res158.png"),
        GameItem(159, "Overtime", "https://api.resources-game.ch/resimg/res159.png"),
        GameItem(160, "Guest Workers", "https://api.resources-game.ch/resimg/res160.png"),
        GameItem(161, "Wage Subsidy", "https://api.resources-game.ch/resimg/res161.png")
    )

    fun getIconUrlForResource(resourceID: Int): String? {
        return items.find { it.id == resourceID }?.iconUrl
    }

    fun getBaseEarningsPerHour(resourceID: Int): Double {
        return items.find { it.id == resourceID }?.baseEarningsPerHour ?: 0.0
    }

    fun getBaseOutputPerHour(resourceID: Int): Double {
        return items.find { it.id == resourceID }?.baseOutputPerHour ?: 0.0
    }
}
